version: '3.8'

services:
  ggdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ggdb
    ports:
      - 3307:3306

  app:
    build: .
    depends_on:
      - ggdb
    ports:
      - 8080:8080
